### ISSUE TITLE
Active record query by string

### ISSUE THREAD

**Issue by benbonnet** [bithavoc/multilang-hstore#15]
Having set `multilang   :title`on the item model, with quite a standard query :
`Item.where("title = ?", 'string')`

I get the following :

```
ActiveRecord::StatementInvalid: PG::InternalError: ERROR:  Unexpected end of string
LINE 1: SELECT "items".* FROM "items" WHERE (title = 'string') ORDER ...
```

Can I believe this is due to the multilang/hstore settings ? What can be done do use this type of query ?

**Comment by bithavoc** [comment]
I believe you'd need to use an special operator for that, check out http://www.postgresql.org/docs/9.0/static/hstore.html
